services:
  # Servicio del Backend
  backend:
    build: ./backend
    container_name: kanban-backend
    ports:
      - "3000:3000"
    volumes:
      # Montamos el volumen para que la base de datos SQLite persista
      # si el contenedor se reinicia.
      - ./backend/prisma:/app/prisma
    restart: unless-stopped

  # Servicio del Frontend
  frontend:
    build: ./frontend
    container_name: kanban-frontend
    ports:
      # Mapeamos el puerto 80 del contenedor (Nginx) al puerto 5173 de nuestra máquina
      - "5173:80"
    depends_on:
      # Le decimos a Docker que inicie el backend antes que el frontend
      - backend
    restart: unless-stopped
